### PR TITLE
Calculate idle time when set instead of every cycle

### LINKED ISSUE #667: IdleLEDs timeout maxes out at 10 seconds
As per [this thread](https://community.keyboard.io/t/very-aggressive-power-management/3031), the `IdleLEDs` timeout maxes out at just over 10 seconds. This is due to an incorrect typecasting:

```c++
uint32_t(idle_time_limit * 1000)
```

It's also worth pointing out that the way `IdleLEDs` computes the timeout is inefficient, with the conversion and multiplication occurring each cycle.

### PR DESCRIPTION
**Pull request by tiltowait**
Wrap the `idle_time_limit` property in a getter and setter that automatically converts to milliseconds. This way, we avoid converting inside `beforeEachCycle()`, slightly increasing efficiency.

Also fixes #667.

Signed-off-by: tiltowait <tiltowaitt+github@icloud.com>

### CODE REVIEW

**Comment by gedankenexperimenter** [comment]
The coding style document indicates that the method should be named `setIdleTimeLimit()`, not `set_idle_time_limit`. It should probably set both `idle_time_limit_` and `idle_time_limit`, for backwards compatibility.

Also, there's probably no need for the `getIdleTimeLimit()` method, but it ought to get optimized out anyway, so I suppose it doesn't hurt.

File: src/kaleidoscope/plugin/IdleLEDs.cpp [hunk 1]
```diff
@@ -21,12 +21,20 @@
...
-uint16_t IdleLEDs::idle_time_limit = 600; // 10 minutes
+uint32_t IdleLEDs::idle_time_limit_ = 600000; // 10 minutes
 uint32_t IdleLEDs::start_time_ = 0;
 
+uint16_t IdleLEDs::idle_time_limit() {
+  return uint16_t(idle_time_limit_ / 1000);
+}
+
+void IdleLEDs::set_idle_time_limit(uint16_t new_limit) {
+  idle_time_limit_ = (uint32_t)new_limit * 1000;
```
Comment (gedankenexperimenter) [inline src/kaleidoscope/plugin/IdleLEDs.cpp]: Might it be better to simply make `new_limit` parameter a `uint32_t`?

**Comment by gedankenexperimenter** [comment]
Regarding the name of the new method — maybe it would be good to make it clearer that its parameter is in seconds by including that in the name, because most timeouts in Kaleidoscope are in milliseconds. Something like `setIdleSecondsBeforeLedsOff()` (that's awkward, but more specific).

**Comment by tiltowait** [comment]
@algernon Regarding keeping the property public for compatibility, what's worse: A compiler error that forces the user to do a little digging; or no error, but unexpected behavior when their LEDs turn off in 1/1000 the time they expect? I'm open to either solution.

Granted, this will only affect people who change the default value.

@gedankenexperimenter What about `setIdleTimeoutSeconds()`?

File: src/kaleidoscope/plugin/IdleLEDs.cpp (hunk 1 above)
Comment (tiltowait) [reply src/kaleidoscope/plugin/IdleLEDs.cpp]: I made it `uint16_t` to match the data type of the original, public property, but there's no reason it needs to stay that way. Thanks.

**Comment by obra** [comment]
@algernon does tihs look better?

**Comment by algernon** [comment]
It does look so much better, that I'm merging it. Thank you, and sorry for taking this long!
