### PR TITLE
Stalker: keep LED bright while key is held

### LINKED ISSUE #1342: Stalker LED effect no longer stays full brightness on key hold
**Describe the bug**
The behaviour of the stalker LED effect (my favourite!) has changed at some point between last time I updated my Model 01s and when I finally got around to setting up my Model 100 a month or two ago.

Digging in the code it looks like the change was semi-intentionally made by @gedankenexperimenter in 2073c4f8 while adapting the plugins to KeyEvent handlers; see his comment here:

https://github.com/keyboardio/Kaleidoscope/blob/master/plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp#L54L57

I think it's a shame! This is my favourite LED plugin, and I use it by default. I'm hoping the above was meant as a temporary change so those updates could be made swiftly. But I wonder if there's a way to make it behave like it used to?

**To Reproduce**
Enable the stalker effect. (I'm using the blazing trail variant.)
Press and hold a key. See it start at full brightness and decay over a few seconds.
Release the key. See it jump back up to full brightness and start decaying again.

**Expected behavior**
Key lights up full brightness on press and stays full brightness on hold.
Brightness decay starts on release.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04
 - Device Keyboardio Model 100

**Additional context**

### PR DESCRIPTION
**Pull request by tremby**
This closes #1342.

Thanks to @algernon for guidance. But any bugs are mine not his.

Questions:

- Is it worth removing the event handler? If we are setting the intensity to max while the key is held, I'm not sure whether the event handler (which sets it to max on press and again on release) is adding anything. Maybe it adds a fraction more responsiveness?
- Is `update` the right place for this? I've read also of `beforeSyncingLeds` and `afterEachCycle`, and I don't know which is most appropriate.

### CODE REVIEW

**Comment by tremby** [comment]
Forgot to mention: this is how it used to be before https://github.com/keyboardio/Kaleidoscope/commit/2073c4f85537e07b14d44b589ef44d98a003776d#diff-8ad5917f582836d9d7f56d572e4f08b9d7c15728ac75ec22bb1fab809f3d2ce9

File: plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp [hunk 1]
```diff
@@ -71,6 +69,11 @@ void StalkerEffect::TransientLEDMode::update() {
 
   for (auto key_addr : KeyAddr::all()) {
     uint8_t step = map_[key_addr.toInt()];
+
```
Comment (obra) [inline plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp:72]: @tremby would you mind adding a  comment here explaining what's happening?

File: plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp [hunk 2]
```diff
@@ -51,9 +52,6 @@ EventHandlerResult StalkerEffect::onKeyEvent(KeyEvent &event) {
   if (::LEDControl.get_mode_index() != led_mode_id_)
     return EventHandlerResult::OK;
 
-  // The simplest thing to do is trigger on both press and release. The color
-  // will fade while the key is held, and get restored to full brightness when
-  // it's released.
   ::LEDControl.get_mode<TransientLEDMode>()->map_[event.addr.toInt()] = 0xff;
```
Comment (obra) [inline plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp:55]: I do feel like, for clarity, if this is setting the key to full brightness on release, even when we don't need it to, it's worth a comment explaining what's going on, so that future hackers don't need to go spelunking too deeply for intent.

Comment (tremby) [reply plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp:55]: This comment was added when the API changed such that `onKeyEvent` only fires on press and release, whereas before that change it used to fire continuously while held too. So that comment was added to describe the degraded behaviour it had since that change.

I could certainly add a comment here saying this lights it up on press and release, but isn't that just what `onKeyEvent` means anyway, so wouldn't that be obvious to someone who knows the API?

But what if instead we move the entire `onKeyEvent` handler? I don't think it adds anything. I just tried with it entirely commented out in the cpp and h file and it's working just fine.

File: plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp (hunk 1 above)
Comment (tremby) [reply plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp:72]: Sure.

File: plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp (hunk 2 above)
Comment (tremby) [reply plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp]: I added a commit removing the handler. Let me know what you think.

File: plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp (hunk 1 above)
Comment (tremby) [reply plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp:57]: I added a comment. Honestly I am not 100% certain that `live_keys` and `Key_Inactive` mean exactly what I think they do, so please do review! I am not well versed in the Kaleidoscope API.

**Comment by tremby** [comment]
Oops, I'm not used to signing commits. Squashed and signed.

File: plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp (hunk 2 above)
Comment (obra) [reply plugins/Kaleidoscope-LED-Stalker/src/kaleidoscope/plugin/LED-Stalker.cpp]: If it still works right without the handler, then I approve :)
